version: 1

goos: darwin
goarch: arm64

main: ./cmd/aileron/
binary: aileron-{{ .Os }}-{{ .Arch }}

env:
  - GO111MODULE=on
  - CGO_ENABLED=0

flags:
  - -trimpath
  - -tags=netgo

ldflags:
  - "-w"
  - "-s"
  - "-extldflags \"-static\""
  - "-X main.version={{ .Env.VERSION }}"
