name: QEMU

on: push

jobs:
  unit:
    name: QEMU
    runs-on: ubuntu-latest
    timeout-minutes: 30
    strategy:
      matrix:
        arch:
          - linux/amd64
          - linux/arm64
          - linux/riscv64
          - linux/ppc64le
          - linux/s390x
          - linux/386
          - linux/arm/v7
          - linux/arm/v6
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: docker/setup-qemu-action@v3
        with:
          platforms: ${{ matrix.arch }}
      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: ./go.mod
      - run: go run ./...
