name: Runner

on: [push, workflow_dispatch]

jobs:
  unit:
    name: Runner
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 5
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: ./go.mod
      - run: go run ./...

      # Docker is available on linux and windows by default.
      # But not on macos.
      - name: Install docker if macos
        run: test $(go env GOOS) = "darwin" &&  brew install docker
      - name: Docker run
        run: docker run --rm  "golang:latest" uname -r
