name: Runner

on: push

jobs:
  unit:
    name: Runner
    runs-on: ${{ matrix.os }}-latest
    timeout-minutes: 5
    strategy:
      matrix:
        os:
          - ubuntu
          - windows
          - macos
    steps:
      - run: git config --global core.autocrlf false
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          check-latest: true
          go-version-file: ./go.mod
      - run: go run ./...

      # Additional example to run with docker.
      - uses: docker/setup-buildx-action@v3
      - name: Docker run
        run: docker run --rm  "golang:latest" uname -r
