name: SLSA

on: push

permissions:
  id-token: write
  contents: write
  actions: read

jobs:
  build:
    uses: slsa-framework/slsa-github-generator/.github/workflows/builder_go_slsa3.yml@v1.10.0
    strategy:
      matrix:
        os:
          - linux
          - windows
          - darwin
        arch:
          - 386
          - amd64
          - arm
          - arm64
          - ppc64
          - ppc64le
          - riscv64
          - s390x
        exclude:
          - os: windows
            arch: [ppc64, ppc64le, riscv64, s390x]
          - os: darwin
            arch: [386, arm, ppc64, ppc64le, riscv64, s390x]
    with:
      go-version-file: ./go.mod
      config-file: .github/targets/${{matrix.os}}.yml
      evaluated-envs: "VERSION:v0.0.0, ARCH:${{matrix.arch}}"
      draft-release: true
